/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;
//import java.awt.PopupMenu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
//import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
//import javax.swing.JOptionPane;
//import java.util.Vector;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author myominkhaing
 */
public class frmCompanyData extends javax.swing.JFrame {
    private final String url = "jdbc:postgresql://localhost/POS_DB";
    private final String user = "postgres";
    private final String password = "postgre";
    private String ComID;
    private String ComName;
    private static final String createTableSQL = "CREATE TABLE TBL_Company " +
        "(ID INT PRIMARY KEY ," +
        " NAME TEXT, " +
        " COUNTRY VARCHAR(50), " +
        " Remark VARCHAR(50))";
    private String insertCompanySQL;
    private String GetFristCompanySQL;
//    private String GetLastCompanySQL;
//    private String getDataCompanySQL;
    
    ResultSet RS;
    
    PreparedStatement pst;
//    Statement st;
    ResultSet rst = null;
    databaseConnection dbc = new databaseConnection();
    Connection connDbc = null;
    /**
     * Creates new form NewJFrame
     */
    public frmCompanyData() {
        initComponents();
        connDbc = dbc.databaseConn();
        getallData();
    }
    public void clearTable()
{
    DefaultTableModel dm = (DefaultTableModel) jtbl_Company.getModel();
    dm.getDataVector().removeAllElements();
    revalidate();
}
private void getallData(){
    try  {

           String sqlSelectDataFromDatabase = "Select \"COM_ID\", \"COM_NAME\" from \"COM_TBL\"";
           pst = connDbc.prepareStatement(sqlSelectDataFromDatabase);
           rst = pst.executeQuery();
           clearTable(); // To Clear Existing Data
           while(rst.next()) {
               String Companyname = rst.getString("COM_ID");
               String CompanyID = rst.getString("COM_NAME");
           

               DefaultTableModel dftable = (DefaultTableModel) jtbl_Company.getModel();
               Object[] obj = {Companyname,CompanyID};
               dftable.addRow(obj);
                   }
             } catch (SQLException e) {
                 printSQLException(e);
       }
//        frmCompanyData Cdata=new frmCompanyData();
//               
//        String [] columnNames = {"ID","Name"};
//        PreparedStatement pst;
//   try (Connection connection = DriverManager.getConnection(url , user , password);
//
//        // Step 2:Create a statement using connection object
//        Statement statement = connection.createStatement();)
//        {
//        String SQLQuery="Select id, Name from tbl_company";
//        pst=connection.prepareStatement(SQLQuery);
//        RS = pst.executeQuery();
//        DefaultTableModel model=(DefaultTableModel) jtbl_Company.getModel();
//
//        model.addColumn("ID");
//        model.addColumn("name");
//        Vector<Object> row= new Vector<Object>();
//
//        while (RS.next()){
//
//            String ID= RS.getString("id");
//            String Name=RS.getString("name");
//            Object[] obj = {ID,Name};
//
//            model.setColumnIdentifiers(columnNames);
//            model.addRow(obj);
//
//            //Object tbData[] = {id,name};
//        }
//        jtbl_Company.setModel(model);
//        pack();
//
//       RS.close();
//        statement.close();
//        connection.close();
//    } catch (SQLException e) {
//
//        // print SQL exception information
//        printSQLException(e);
//    }
//          
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_Clear = new javax.swing.JToggleButton();
        btn_Save = new javax.swing.JButton();
        btn_Display = new javax.swing.JButton();
        btn_Update1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLbl_CompanyName = new javax.swing.JLabel();
        jLbl_CompanyID = new javax.swing.JLabel();
        txt_CompanyID = new javax.swing.JTextField();
        txt_CompanyName = new javax.swing.JTextField();
        btn_First = new javax.swing.JButton();
        btn_previous = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_Last = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_Company = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Company Information");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_Clear.setActionCommand("Clear");
        btn_Clear.setLabel("Clear");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        btn_Save.setActionCommand("Save");
        btn_Save.setLabel("Save");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_Display.setActionCommand("Save");
        btn_Display.setLabel("Display");
        btn_Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DisplayActionPerformed(evt);
            }
        });

        btn_Update1.setText("Exit");
        btn_Update1.setActionCommand("Save");
        btn_Update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Update1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Display)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Update1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Clear)
                    .addComponent(btn_Save)
                    .addComponent(btn_Display)
                    .addComponent(btn_Update1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLbl_CompanyName.setText("Company Name");

        jLbl_CompanyID.setText("Company ID");

        txt_CompanyID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_CompanyID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CompanyIDActionPerformed(evt);
            }
        });

        txt_CompanyName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLbl_CompanyID)
                    .addComponent(jLbl_CompanyName))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_CompanyID)
                    .addComponent(txt_CompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl_CompanyID))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl_CompanyName))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btn_First.setText("First");
        btn_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FirstActionPerformed(evt);
            }
        });

        btn_previous.setText("<< ");
        btn_previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_previousActionPerformed(evt);
            }
        });

        btn_next.setText(" >>");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_Last.setText("Last");
        btn_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LastActionPerformed(evt);
            }
        });

        jtbl_Company.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ));
        jtbl_Company.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtbl_Company);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_First, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_previous, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_next, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Last, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_First)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_previous)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_next)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Last))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        // TODO add your handling code here:
       frmCompanyData Cdata=new frmCompanyData();
       
       Cdata.insertCompanySQL=  " INSERT INTO tbl_company(" +
	"id, name, country, remark)"+
	"VALUES ("+ txt_CompanyID.getText() +", '"+ txt_CompanyName.getText()+"', 'Myanamr', 'Testing');";
    System.out.println(Cdata.insertCompanySQL);

        try {
            Cdata.ExecuteQuery(Cdata.insertCompanySQL);
              this.clear();
        } catch (SQLException e) {
        // print SQL exception information
        printSQLException(e);
    }
    getallData();

    }//GEN-LAST:event_btn_SaveActionPerformed

    private void txt_CompanyIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CompanyIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CompanyIDActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
   // TODO add your handling code here:
   this.clear();
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FirstActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
               frmCompanyData Cdata=new frmCompanyData();
       Cdata.GetFristCompanySQL=  "Select * from tbl_company order by id asc limit 1";
    //System.out.println(Cdata.GetFristCompanySQL);

        try {
           Cdata.getQuery(Cdata.GetFristCompanySQL);
            txt_CompanyID.setText(Cdata.ComID);
            txt_CompanyName.setText(Cdata.ComName);

        } catch (SQLException e) {
        // print SQL exception information
        printSQLException(e);
    }
    }//GEN-LAST:event_btn_FirstActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previousActionPerformed
        // TODO add your handling code here:
              
       
            

    }//GEN-LAST:event_btn_previousActionPerformed

    private void btn_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LastActionPerformed
        // TODO add your handling code here:
               frmCompanyData Cdata=new frmCompanyData();
       Cdata.GetFristCompanySQL=  "Select * from tbl_company order by id desc limit 1";
    //System.out.println(Cdata.GetFristCompanySQL);

        try {
            Cdata.getQuery(Cdata.GetFristCompanySQL);
            txt_CompanyID.setText(Cdata.ComID);
            txt_CompanyName.setText(Cdata.ComName);

        } catch (SQLException e) {
        // print SQL exception information
        printSQLException(e);
    }
    }//GEN-LAST:event_btn_LastActionPerformed

    private void btn_DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DisplayActionPerformed
        // TODO add your handling code here:
      //  txt_CompanyID.setText("text");
      frmCompanyData Cdata=new frmCompanyData();
Cdata.getallData();
    }//GEN-LAST:event_btn_DisplayActionPerformed

    private void btn_Update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Update1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_Update1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCompanyData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCompanyData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCompanyData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCompanyData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCompanyData().setVisible(true);
            }
        });
                       
    }
//    public void DoConnect(){
//        String SQLQuery="Select * from tbl_company order by id asc";
//        try (Connection connection = DriverManager.getConnection(url , user , password);
//
//        // Step 2:Create a statement using connection object
//        Statement statement = connection.createStatement();) {
//
//        // Step 3: Execute the query or update query
//        RS= statement.executeQuery(SQLQuery);
//        
//    //    connection.close();
//    } catch (SQLException e) {
//
//        // print SQL exception information
//        printSQLException(e);
//    }
//    }
    public void ExecuteQuery(String Query) throws SQLException {

    System.out.println(createTableSQL);
    // Step 1: Establishing a Connection
    try (Connection connection = DriverManager.getConnection(url , user , password);
         

        // Step 2:Create a statement using connection object
        Statement statement = connection.createStatement();) {

        // Step 3: Execute the query or update query
        statement.execute(Query);
        connection.close();
    } catch (SQLException e) {

        // print SQL exception information
        printSQLException(e);
    }
}
public void getQuery(String SQLQuery)throws SQLException{
    
    System.out.println(SQLQuery);
    // Step 1: Establishing a Connection
    try (Connection connection = DriverManager.getConnection(url , user , password);

        // Step 2:Create a statement using connection object
        Statement statement = connection.createStatement();) {

        // Step 3: Execute the query or update query
        RS= statement.executeQuery(SQLQuery);
        if (RS.next()) {
            ComID =RS.getString("id") ;
            ComName=RS.getString("name");
            System.out.println(RS.getString("id"));
          System.out.println(RS.getString("name"));
         }
    //    connection.close();
    } catch (SQLException e) {

        // print SQL exception information
        printSQLException(e);
    }
}
public static void printSQLException(SQLException ex) {
    for (Throwable e: ex) {
        if (e instanceof SQLException) {
            e.printStackTrace(System.err);
            System.err.println("SQLState: " + ((SQLException) e).getSQLState());
            System.err.println("Error Code: " + ((SQLException) e).getErrorCode());
            System.err.println("Message: " + e.getMessage());
            Throwable t = ex.getCause();
            while (t != null) {
                System.out.println("Cause: " + t);
                t = t.getCause();
            }
        }
    }
}
private void clear() {
			txt_CompanyID.setText("");
			txt_CompanyName.setText("");
		
		}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_Clear;
    private javax.swing.JButton btn_Display;
    private javax.swing.JButton btn_First;
    private javax.swing.JButton btn_Last;
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_Update1;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_previous;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLbl_CompanyID;
    private javax.swing.JLabel jLbl_CompanyName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbl_Company;
    private javax.swing.JTextField txt_CompanyID;
    private javax.swing.JTextField txt_CompanyName;
    // End of variables declaration//GEN-END:variables
    
}
